EscalArt/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
# from .views import  AddFollower, AddLike, AddLikeComment, CategoriaSearch, RemoveFollower, ResponderComentarioView, Room, UserSearch, cambiar_pass, chats, configuracion, delete_comision, estadoComisionArt, estadoComisionCli, home , ayudacliente,  perfil_cliente, presentacion, publicacion, publicacionHome, seleccionarC, tagged
# from .views import perfil
# from .views import RegistrarUsuario,ayudacliente,delete_publicacion,datosCliente
from .views import *


urlpatterns =[
    path('',home, name="home"),
    path('perfil/<id>',perfil, name="perfil"),
    path('registro/',RegistrarUsuario,name="registro"),
    path('ayudacliente',ayudacliente,name="ayudacliente"),
    path('perfil/<artista>/publicacion/<post>',publicacion,name="publicacion"),
    path('home/<artista>/publicacion/<post>',publicacionHome,name="publicacionHome"),
    path('perfilCli/<id>',perfil_cliente,name="perfil_cliente"),
    path('borrar-publicacion/<id>',delete_publicacion,name='delete_publicacion'),
    path('publicacion/<int:pk>/like',AddLike.as_view(),name='LikePublicacion'),
    path('perfil/<id>/followers/add', AddFollower.as_view(),name='add-follower'),
    path('perfil/<id>/followers/remove', RemoveFollower.as_view(),name='remove-follower'),
    path('buscar/',UserSearch.as_view(),name='buscar-perfil'),
    path('tag/<slug:slug>/', tagged, name="tagged"),
    path('comentario/<int:pk>/like',AddLikeComment.as_view(),name='likeComment'),
    path('perfil/<artista>/publicacion/<int:post_pk>/comentario/<int:pk>/responder',ResponderComentarioView.as_view(),name='responder-comentario'),
    path('chat',chats.as_view(),name="chats"),    
    path('chat/<str:room_name>/',Room.as_view(),name='room'),
    path('datosCliente/<id>',datosCliente,name="datosCliente"),
    path('datosCliente/<idCliente>/comision/<idComision>',estadoComisionArt,name='estadoComisionArt'),
    path('borrar-comision/<id>',delete_comision,name='delete_comision'),
    path('perfilCli/<id>/comision/<idComision>',estadoComisionCli,name='estadoComisionCli'), 
    path('sobre_nosotros',sobre_nosotros,name="sobre_nosotros"),

    path('configuracion',configuracion.as_view(),name="configuracion"),
    path('buscarcategoria/',CategoriaSearch.as_view(),name='buscar-categoria'),

    path('seleccionarC',seleccionarC,name="seleccionarC"),
    path('presentacion',presentacion,name="presentacion"),
    path('configuracion/cambiar_pass',cambiar_pass.as_view(),name="cambiar_pass"),
    path('accounts/password_change/done/',auth_views.PasswordChangeDoneView.as_view(template_name='registration/cambiar_contra_done.html'),name="cambiar_pass_done"),
    path('reset_password/',auth_views.PasswordResetView.as_view(template_name="registration/cambiar_pass.html"),name='reset_password'),
    path('accounts/password_reset/done/',auth_views.PasswordResetDoneView.as_view(template_name="registration/cambiar_pass_sent.html"),name='password_reset_done'),
    path('accounts/reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name="registration/cambiar_pass_form.html"),name='password_reset_confirm'),
    path('accounts/reset/done/',auth_views.PasswordResetCompleteView.as_view(template_name="registration/cambiar_pass_done.html"), name='password_reset_complete'),
    
]

ProyectoAPT/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('EscalArt.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

EscalArt/models.py
from typing_extensions import Self
from django.utils import timezone
from enum import unique
from lib2to3.pytree import Base
from mailbox import mbox
from operator import truediv
from pyexpat import model
from tabnanny import verbose
from tkinter import CASCADE
from turtle import Turtle
from webbrowser import get
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.test import TransactionTestCase
from requests import request
from taggit.managers import TaggableManager
from django.db.models.signals import post_save
from django.dispatch import receiver
# from typing_extensions import Self

# Create your models here.
class UsuarioManager(BaseUserManager):
    def create_user(self,email,username,nombre,tipoCuenta,password = None):
        if not email:
            raise ValueError('El usuario debe tener un correo electronico')
        
        usuario = self.model(
            username=username,
            email= self.normalize_email(email),
            nombre =nombre,
            tipoCuenta = TipoCuenta.objects.get(idTipoCuenta =tipoCuenta)
        )
        

        usuario.set_password(password)
        usuario.save()
        

        return usuario
    
    
    def create_superuser(self,username,email,nombre,tipoCuenta,password):
        usuario = self.create_user(
            email,
            username=username,
            nombre=nombre,
            tipoCuenta = tipoCuenta,
            password=password

        )
        usuario.usuario_administrador = True
        usuario.save()
        return usuario


# class Categoria(models.Model):
#     idCategoria = models.AutoField(primary_key=True,verbose_name='Id Categoría')
#     nombreCategoria = models.CharField(max_length=50,verbose_name='Nombre Categoría')

#     def __str__(self):
#         return  self.nombreCategoria

class TipoCuenta(models.Model):
    idTipoCuenta = models.AutoField(primary_key=True, verbose_name='Id Tipo Cuenta')
    tipoCuenta = models.CharField(max_length=50,verbose_name='Tipo Cuenta')

    def __str__(self):
        return  self.tipoCuenta

class Usuario(AbstractBaseUser):
    idUser = models.AutoField(primary_key=True,verbose_name='Id Usuario')
    username = models.CharField('Nombre de usuario', unique=True,max_length=50)
    email = models.EmailField('Correo Electronico',max_length=254,unique=True)
    nombre = models.CharField('Nombre completo', max_length=200, blank=True,null=True)
    imagen = models.ImageField('Foto de Perfil', upload_to=None, max_length=200, blank=True, null=True)
    tipoCuenta = models.ForeignKey(TipoCuenta,on_delete=models.CASCADE,verbose_name='Tipo de cuenta')
    is_active = models.BooleanField(default=True)
    usuario_administrador = models.BooleanField(default=False)
    objects = UsuarioManager()


    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email','nombre','tipoCuenta']

    def __str__(self):
        return f'{self.nombre}'

    def has_perm(self,perm,obj = None):
        return True
    
    def has_module_perms(self,app_label):
        return True
    
    @property
    def is_staff(self):
        return self.usuario_administrador

    
class Publicacion(models.Model):
    idPublicacion = models.AutoField(primary_key= True, verbose_name='Id Publicacion')
    descripcion = models.CharField('Descripcion', max_length=250, blank=True,null=True)
    titulo = models.CharField('Titulo Publicacion', max_length=150)
    imagen = models.ImageField('Imagen', upload_to=None, max_length=200, blank = False, null = False)
    cantLikes = models.ManyToManyField(Usuario,blank=True,verbose_name='likes',related_name='likes')
    idUser = models.ForeignKey(Usuario,on_delete=models.CASCADE,verbose_name='Id Usuario')
    tags = TaggableManager(blank=True)
    fechaCreacion = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f'{self.titulo,self.idUser}'

class Perfil(models.Model):
    idPerfil = models.AutoField(primary_key = True, verbose_name = 'Id Perfil')
    # seguidos = models.ManyToManyField(Usuario, blank=True, related_name='seguidos',verbose_name='nro Seguidos')
    seguidores = models.ManyToManyField(Usuario, blank=True, related_name='seguidores',verbose_name='nro seguidores')
    calificacion = models.IntegerField('Calificacion')
    img_header = models.ImageField('Header', upload_to='index', max_length=200, blank=True, null=True)
    biografia = models.CharField('Biografia', max_length=250, blank=True,null=True)
    idUser = models.ForeignKey(Usuario,on_delete=models.CASCADE,verbose_name='Id user',unique = True)
    showTags = models.BooleanField(default=False)
    tags = TaggableManager(blank=True)

    def __str__(self):
        return f'{self.idPerfil,self.idUser}'

# class Usuario_Categoria(models.Model):
#     idUser = models.ForeignKey(Usuario,on_delete=models.CASCADE,verbose_name='Id user')
#     idCategoria = models.ForeignKey(Categoria, on_delete=models.CASCADE, verbose_name='Id Categoria')

#     def __str__(self):
#         return f'{self.idUser,self.idCategoria}'

# class Publicacion_Categoria(models.Model):
#     idCategoria = models.ForeignKey(Categoria, on_delete=models.CASCADE, verbose_name='Id Categoria')
#     idPublicacion = models.ForeignKey(Publicacion, on_delete=models.CASCADE, verbose_name='Id Publicacion')

#     def __str__(self):
#         return f'{self.idPublicacion,self.idCategoria}'

class Comentarios(models.Model):
    comentario = models.CharField('Comentario', max_length=250)
    fechaCreacion = models.DateTimeField(default=timezone.now)
    cantLikes = models.ManyToManyField(Usuario,blank=True,verbose_name='likes',related_name='CommentLikes')
    idPublicacion = models.ForeignKey(Publicacion, on_delete=models.CASCADE, verbose_name='Id Publicacion')
    idUser = models.ForeignKey(Usuario,on_delete=models.CASCADE,verbose_name='Id user')
    parent = models.ForeignKey('self',on_delete=models.CASCADE,blank=True,null=True,related_name='+')


    def __str__(self):
        return f'{self.idUser,self.comentario}'

    @property
    def children(self):
        return Comentarios.objects.filter(parent=self).order_by('-fechaCreacion').all()
    
    @property
    def is_parent(self):
        if self.parent is None:
            return True       
        return False

class EstadoComision(models.Model):
    idEstado = models.AutoField(primary_key=True, verbose_name='Id Estado Comision')
    estado = models.CharField('Estado',max_length=150)
    def __str__(self):
        return f'{self.estado}'

class Comision(models.Model):
    idComision = models.AutoField(primary_key=True, verbose_name='Id Comision')
    idEstado = models.ForeignKey(EstadoComision,on_delete=models.CASCADE,verbose_name='Id Estado Comision')
    idArtista = models.ForeignKey(Usuario,on_delete=models.CASCADE, verbose_name='Id Artista')
    def __str__(self) :
        return f'{self.idComision,self.idArtista,self.idEstado.estado}'

class Comision_Cliente(models.Model):
    idComision = models.ForeignKey(Comision,primary_key=True,on_delete=models.CASCADE,verbose_name='Id Comision')
    idCliente = models.ForeignKey(Usuario,on_delete=models.CASCADE,verbose_name='Id Cliente')
    def __str__(self) :
        return f'{self.idComision,self.idCliente}'


class Solicitud(models.Model):
    idSolicitud = models.CharField(primary_key=True,verbose_name='Id Solicitud',max_length=150)
    idCliente = models.ForeignKey(Usuario,on_delete=models.CASCADE,verbose_name='Id Cliente')
    usernameArtista = models.CharField('Username Artista',max_length=150)

    def __str__(self):
        return f'{self.idCliente,self.usernameArtista}'

class Referencia(models.Model):
    idReferecia = models.AutoField(primary_key=True,verbose_name='Id Referencia')
    img_referencia = models.ImageField('Referencia', upload_to='index', max_length=200)
    usernameArtista = models.CharField('Username Artista',max_length=150)
    idUser = models.ForeignKey(Usuario,on_delete=models.CASCADE,verbose_name='Id Cliente')

    def __str__(self):
        return f'{self.img_referencia,self.idUser,self.usernameArtista}'

class Guardado(models.Model):
    idGuardado = models.CharField(primary_key=True,verbose_name='Id Guardado',max_length=150)
    idUser = models.ForeignKey(Usuario,on_delete=models.CASCADE,verbose_name='Id usuario')
    idPublicacion = models.ForeignKey(Publicacion,on_delete=models.CASCADE,verbose_name='Id publicacion')

    def __str__(self):
        return f'{self.idUser,self.idPublicacion}'


class Review(models.Model):
    idPerfil = models.ForeignKey(Perfil,on_delete=models.CASCADE)
    idUser = models.ForeignKey(Usuario,on_delete=models.CASCADE)
    review = models.TextField(max_length=500,blank=True)
    rating = models.IntegerField()
    fechaCreacion = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f'{self.rating}'

class Review_cliente(models.Model):
    idPerfil = models.ForeignKey(Perfil,on_delete=models.CASCADE)
    idUser = models.ForeignKey(Usuario,on_delete=models.CASCADE)
    review = models.TextField(max_length=500,blank=True)
    rating = models.IntegerField()
    fechaCreacion = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f'{self.rating}'


class Chat(models.Model):
    contenido = models.CharField(max_length=1000)
    img_referencia = models.ImageField('Referencia', upload_to=None, max_length=200, blank=True, null=True)
    fecha = models.DateTimeField(auto_now=True)
    idUser = models.ForeignKey(Usuario,on_delete=models.CASCADE)
    room = models.ForeignKey('ChatRoom',on_delete=models.CASCADE)

class ChatRoom(models.Model):
    nombre = models.CharField(max_length=255)
    

EscalArt/templates/escalArt/estadoComisionArt.html
{% extends 'escalArt/datosCliente.html' %} {% load static %} {% block content %}

<div class="comisiones">

    {% if comision.idComision.idEstado.estado == "cancelada" %}
    <ul>
        <li class="li-left"><i class="fa-solid fa-box-archive" style="color: #bc0b0b;"></i>
            <span class="span-left span-dis" style="background: #bc0b0b;"></span>
            <p style="color: #bc0b0b;">Tu Comision ha sido recibida</p>


            



        </li>
        <li class="li-left">

            <i class="fa-solid fa-spinner" style="color: #bc0b0b;"></i>
            <span class="span-centro span-dis" style="background: #bc0b0b;"></span>
            <p style="color: #bc0b0b;">Tu comision está en desarrollo</p>
            <span class="span-centro_2" style="background: #bc0b0b;"></span>

        </li>
        <li class="li-left">

            <i class="fa-solid fa-paper-plane" style="color: #bc0b0b;"></i>
            <span class="span-right span-dis" style="background: #bc0b0b;"></span>
            <p style="color: #bc0b0b;"> ¡Tu comisión ya esta lista! </p>
           
            <!--  -->

        </li>
    </ul>
    {% else %}
    <ul>
        <li class="li-left"><i class="fa-solid fa-box-archive"></i>
            <span class="span-left span-dis"></span>
            <p>Tu Comision ha sido recibida</p>


           



        </li>
        <li class="li-left">
            {% if comision.idComision.idEstado.estado == "en desarrollo" or comision.idComision.idEstado.estado == "terminada" %}
            <i class="fa-solid fa-spinner"></i>
            <span class="span-centro span-dis"></span>
            <p>Tu comision está en desarrollo</p>
            <span class="span-centro_2"></span> 
            {% else %}
            <i class="fa-solid fa-spinner" style="color: gray;"></i>
            <span class="span-centro span-dis" style="background: gray;"></span>
            <p style="color: gray;">Tu comision está en desarrollo</p>
            <span class="span-centro_2" style="background: gray;"></span>
            <!--  -->
            {%endif%}
        </li>
        <li class="li-left">
            {% if comision.idComision.idEstado.estado == "terminada" %}
            <i class="fa-solid fa-paper-plane"></i>
            <span class="span-right span-dis"></span>
            <p> ¡Tu comisión ya esta lista! </p>
       
            {% else %}
            <i class="fa-solid fa-paper-plane" style="color: gray;"></i>
            <span class="span-right span-dis" style="background: gray;"></span>
            <p style="color: gray;"> ¡Tu comisión ya esta lista! </p>
            
            <!--  -->
            {%endif%}
        </li>
    </ul>
    {% endif %}
    <form  method="POST">
        {% csrf_token %} {{form}}
        <input style="display: none;" type="text" name="comision" value="{{comision.idComision.idComision}}">

        <input type="submit" name="editar" class="btn btn-danger editar-estado-btn btn--3" value="Editar Estado"> {% if comision.idComision.idEstado.estado == "cancelada" %}

        <input type="hidden" name="next" value="/datosCliente/{{userInfo.username}}">
        <td><button type="submit"><a href="{%url 'delete_comision' comision.idComision.idComision %} " >Eliminar</a></button></td>


        {% endif %}


    </form>
</div>

{% endblock %}

EscalArt/templates/escalArt/perfil_cliente.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Perfil</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer"
    />
    <link rel="icon" href="/EscalArt/static/escalArt/img/EscalArt.png">
    <link type="text/css" rel="stylesheet" href="{% static 'EscalArt/css/Menu-Fotter.css' %}">
    <link type="text/css" rel="stylesheet" href="{% static 'EscalArt/css/home.css' %}">
    <link type="text/css" rel="stylesheet" href="{% static 'EscalArt/css/perfil_cliente.css' %}">
    <link type="text/css" rel="stylesheet" href="{% static 'EscalArt/css/publicacion.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@700&family=Roboto+Condensed:wght@300;400&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />

    <!--Iconos-->
    <script src="https://kit.fontawesome.com/943e4f11a2.js" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

</head>

<body>
    <!-- Header -->
    {% include 'escalArt/includes/menu.html' %}
    <div class="scrol"></div>

    {% if userInfo.idUser == user.idUser %}




    <!--Diseño Perfi-->
    <section class="seccion-perfil-usuario">
        <div class="perfil-usuario-header">
            <div class="perfil-usuario-portada">
                <!-- 5 Inicio de for para mostrar los datos en perfil segun el usuario conectado -->
                {% for perfil in perfil %}
                <!-- 6 inicio if para identificar perfil segun user -->
                {% if userInfo.idUser == perfil.idUser.idUser %} {% if perfil.img_header %}<img class="perfil-usuario-portada_2" src="/{{ perfil.img_header }}"> {% else %}
                <img class="perfil-usuario-portada_2" src="{% static 'EscalArt/img/fondodeterminado.jpg' %}" alt=""> {% endif %}


                <!-- 6 FIN if para identificar perfil segun user -->
                {% endif %}
                <!-- 5 FIN ciclo for que lista los perfiles -->
                {% endfor %}
                <div class="perfil-usuario-avatar">

                    {% if userInfo.imagen %}
                    <img src="/{{userInfo.imagen}}" class="foto_perfil" alt="">
                    <!--  -->
                    {% else %}
                    <img src="{% static 'EscalArt/img/perfil.jpg' %}" alt="">
                    <!--  -->
                    {% endif %}

                    <form action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %} {{foto.as_hidden}} <input type="file" id="real-file2" name="pfp" hidden="hidden">
                        <button type="button" class="boton-avatar" id="custom-button2" onclick="MostrarAlerta();">
                            <i class="far fa-image"></i>
                        </button>

                        <div class="div-alerta-img-cli" id="AlertaOk">
                            <h1>¿Quieres cambiar la imagen?</h1>
                            <div class="btn-alet-img-cli">
                                <button onclick="OcultarAlerta();" class="btn-imagen-cli" style="margin-left: 5%;">Cancelar </button>
                                <button onclick="OcultarAlerta();" class="btn-imagen-cli" type="submit" name="fotoPerfil">Aceptar</button>
                            </div>
                        </div>
                    </form>
                </div>
                <form action="" method="POST" enctype='multipart/form-data'>
                    {% csrf_token %} {{edit.img_header.as_hidden}}
                    <input type="file" id="real-file3" name="header" hidden="hidden">
                    <button type="button" class="boton-portada" id="custom-button3" onclick="MostrarAlerta2();">
                        <i class="far fa-image"></i> Cambiar fondo
                    </button>

                    <div class="div-alerta-fondoimg-cli" id="AlertaOk2">
                        <h1>¿Quieres cambiar el fondo?</h1>
                        <div class="btn-alert-fondoimg-cli">
                            <button onclick="OcultarAlerta2();" class="btn-fondoimagen-cli" type="submit" name="EditHeader">Aceptar</button>
                            <button onclick="OcultarAlerta2();" class="btn-fondoimagen-cli" style="margin-left: 5%;">Cancelar </button>
                        </div>
                    </div>

                </form>
            </div>
        </div>
        <div class="perfil-usuario-body">
            <div class="perfil-usuario-bio">
                <h3 class="titulo">{{userInfo.username}}</h3>
                <span class="linea_2"></span>
            </div>
        </div>
    </section>
    <span class="linea"></span>
    <div class="cliente-opt">
        <ul>
            <li onclick="mostrarGuardados();"><i class="fa-solid fa-bookmark"></i>Guardados</li>
            <li onclick="mostrarComisiones();"><i class="fa-solid fa-calendar-check" style="color: #36AE7C;"></i>Estado de Comisiones</li>
            {% if userInfo.tipoCuenta.tipoCuenta == 'artista'%}
            <li onclick="mostrarComisionesTrabajo();"><i class="fa-solid fa-briefcase" style="color: #926D4F;"></i>Comisiones en las que trabajo</li>
            {%endif%}
        </ul>
    </div>
    <!--Galeria de fotos-->
    <section class="galeria_guardados" id="gl-guardados" style="display: none;">
        <section id="galeria">
            {% for g in guardados %}
            <a href="{% url 'publicacion' g.idPublicacion.idUser.username g.idPublicacion.idPublicacion %}" name="idPost" id="idPost"><img src="/{{g.idPublicacion.imagen}}" alt="Galeria de imagenes"></a> {%empty%}
            <h3 class="empty-saves">No hay publicaciones guardadas</h3>
            {%endfor%}


        </section>
        <section id="contenedor-principal">
            <div class="contenedor-interno">
                <img id="img-activa" src="{% static 'EscalArt/img/foto_1.jpg' %}" alt="Galeria de imagenes">
                <button id="btn-cierra" type="button" class="button-cierra">X</button>
                <button id="btn-retrocede" type="button">&lt;</button>
                <button id="btn-adelanta" type="button">&gt;</button>
            </div>
        </section>
    </section>
    <!--Estado Comision-->
    <div class="estado-comision" id="es-comision" style="display: flex;">
        <div class="left">
            <div class="titulo-art">
                <h1>Tus Comisiones</h1>
            </div>
            <div class="estado-comision-lista">
                <ul>
                    {% for c in comCli %}

                    <li>
                        <a href="{% url 'estadoComisionCli' request.user.username c.idComision.idComision %}"> Comision {{c.idComision.idComision}} | {{c.idComision.idArtista.username}}</a>
                    </li>
                    {%empty%}
                    <p class="empty-saves">No tienes ninguna comision de momento</p>


                    <!-- 13 FIN for para listar comisiones -->
                    {% endfor %}


                    <!-- <li><img class="estado_comision-img" src="{% static 'EscalArt/img/perfil.jpg' %}" alt="">[Nombre Artista]</li>
                    <li><img class="estado_comision-img" src="{% static 'EscalArt/img/perfil.jpg' %}" alt="">[Nombre Artista]</li>
                    <li><img class="estado_comision-img" src="{% static 'EscalArt/img/perfil.jpg' %}" alt="">[Nombre Artista]</li>
                    <li><img class="estado_comision-img" src="{% static 'EscalArt/img/perfil.jpg' %}" alt="">[Nombre Artista]</li> -->
                </ul>
            </div>
        </div>
        <div class="right" style="width: 80%;">
            {%block content%}
            <div class="titulo-art" hidden>
                <h1>[Nombre Artista]</h1>
            </div>
            <div class="comisiones" hidden>
                <ul>
                    <li class="li-left"><i class="fa-solid fa-box-archive"></i>
                        <span class="span-left span-dis"></span>
                        <p>Tu Comision ha sido recibida</p>
                    </li>
                    <li class="li-left"><i class="fa-solid fa-spinner"></i>
                        <span class="span-centro span-dis"></span>
                        <p>Tu comision está en desarrollo</p>
                        <span class="span-centro_2"></span>
                    </li>
                    <li class="li-left"><i class="fa-solid fa-paper-plane"></i>
                        <span class="span-right span-dis"></span>
                        <p> ¡Tu comisión ya esta lista! </p>
                    </li>
                </ul>
            </div>

            <div class="comisiones">
                <ul>
                    <li class="lif-left">
                        <h3 class="empty-saves">Elige una comision para revisar su estado!</h3>
                    </li>
                </ul>

            </div>
            {% endblock %}
        </div>
    </div>
    {% comment %} Comisiones en las que trabajo {% endcomment %}

    <div class="div-ec">
        <div class="estado-comision" id="es-comisiontrabajo" style="display: none;">

            <div class="contenedor_comisiones comisiones_new">
                {% for ct in comisionTrabajo %}
                <article class="post users users-ec">
                    <div class="post-body ">
                        <div class="post-container">
                            <a class="column" href="{% url 'estadoComisionArt' ct.comision_cliente_set.all.0.idCliente.username ct.idComision %}">
                            
                        {% if ct.comision_cliente_set.all.0.idCliente.imagen %}
                        <img id="foto-perfil" src="/{{ ct.comision_cliente_set.all.0.idCliente.imagen}}" alt="Galeria de imagenes">
                            {%else%}
                            <img src="{% static 'EscalArt/img/perfil.jpg' %}" id="foto-perfil" alt="">
                        {% endif %}
                            
                    </a>
                            <a style="text-decoration: none;" class="column" href="{% url 'estadoComisionArt' ct.comision_cliente_set.all.0.idCliente.username ct.idComision %}">
                                <h2 id="nombre">Comision {{ct.idComision}}</h2>
                                <h3 class="username nickname">Cliente: @{{ct.comision_cliente_set.all.0.idCliente.username}}</h3>
                            </a>
                        </div>
                        <span class="linea_2"></span>
                        <p style="font-size: 1.5rem; color: #474747;">Estado: {{ct.idEstado.estado}}</p>

                    </div>
                </article>
                {%empty%}
                <h1 class="empty-saves">No estas trabajando en ninguna comision de momento</h1>
                {% endfor %}

            </div>

        </div>
    </div>
    {%else%}
    <br><br><br>
    <br><br><br>
    <br><br> {% endif %}

    <script src="{% static 'EscalArt/js/perfil_cliente.js' %}"></script>
    <script src="{% static 'EscalArt/js/Galeria.js' %}"></script>
    <!--Pie de la pagina-->
    {% include 'escalArt/includes/footer.html' %}


</body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

<!-- menu toggle -->
<script src="{% static 'escalArt/js/menu.js' %}"></script>

</html>